import type { List } from '@prisma/client';

export const FangornDevList = {
	id: '46c40ed5-aa3a-4146-b545-3c428713e9c0',
	name: 'Fangorn',
	points: 750,
	actualPoints: 750,
	game: 'MESBG',
	army: 'Fangorn',
	groups: [
		{
			id: 'RMOLLDUG',
			leader: {
				id: 'HRVUUTVH',
				name: 'Treebeard',
				slot: 'Hero of Legend',
				notes: '',
				amount: 1,
				points: 190,
				equipment: [{ name: 'Merry & Pippin', points: 10 }],
			},
			members: [
				{
					id: 'IAWNLSPY',
					name: 'Beechbone',
					slot: 'Hero of Fortitude',
					amount: 1,
					points: 150,
					equipment: [],
				},
				{
					id: 'FOQQJXSH',
					name: 'Ent',
					slot: 'Warrior',
					notes: '',
					amount: 4,
					points: 100,
					equipment: [],
				},
			],
		},
	],
} as unknown as List;

export const ThorinsDevList = {
	id: '6cae18a1-fba2-480f-b6b0-f32c8f0f7d0c',
	name: 'Thorins',
	points: 750,
	actualPoints: 730,
	game: 'MESBG',
	army: `Thorin's Company`,
	groups: [
		{
			id: 'QTWCWLAI',
			leader: {
				id: 'OORRJYOZ',
				name: 'Thorin Oakenshield',
				slot: 'Hero of Legend',
				notes: '',
				amount: 1,
				points: 100,
				equipment: [
					{ name: 'Orcrist', points: 10 },
					{ name: 'The Oakenshield', points: 5 },
				],
			},
			members: [
				{
					id: 'ZLENOUAS',
					name: 'Dwalin the Dwarf',
					slot: 'Hero of Valour',
					amount: 1,
					points: 95,
					equipment: [],
				},
				{
					id: 'ZZDDQYUY',
					name: 'Gloin the Dwarf',
					slot: 'Hero of Fortitude',
					amount: 1,
					points: 85,
					equipment: [],
				},
				{
					id: 'DYECNTEA',
					name: 'Balin the Dwarf',
					slot: 'Hero of Valour',
					amount: 1,
					points: 40,
					equipment: [],
				},
				{
					id: 'DMYSOBYL',
					name: 'Fili the Dwarf',
					slot: 'Hero of Valour',
					amount: 1,
					points: 50,
					equipment: [],
				},
				{
					id: 'MJNGOEJQ',
					name: 'Kili the Dwarf',
					slot: 'Hero of Valour',
					amount: 1,
					points: 50,
					equipment: [],
				},
				{
					id: 'ROZVKXBP',
					name: 'Nori the Dwarf',
					slot: 'Hero of Fortitude',
					amount: 1,
					points: 55,
					equipment: [],
				},
				{
					id: 'MFZNRSVX',
					name: 'Bilbo Baggins',
					slot: 'Hero of Fortitude',
					amount: 1,
					points: 55,
					equipment: [
						{ name: 'Sting', points: 5 },
						{ name: 'The One Ring', points: 0 },
					],
				},
				{
					id: 'YOEYVLSJ',
					name: 'Oin the Dwarf',
					slot: 'Hero of Fortitude',
					amount: 1,
					points: 50,
					equipment: [],
				},
				{
					id: 'KOZIKWXB',
					name: 'Ori the Dwarf',
					slot: 'Hero of Fortitude',
					amount: 1,
					points: 40,
					equipment: [],
				},
				{
					id: 'YDCBNOFE',
					name: 'Bofur the Dwarf',
					slot: 'Hero of Fortitude',
					amount: 1,
					points: 45,
					equipment: [],
				},
				{
					id: 'DDPMOANB',
					name: 'Bombur the Dwarf',
					slot: 'Hero of Fortitude',
					amount: 1,
					points: 45,
					equipment: [],
				},
			],
		},
	],
} as unknown as List;
